In [73]:
import sys
from utilities import get_data,display_metrics
from sklearn.svm import NuSVC as SVC

def get_model():
    return SVC(kernel = 'poly', degree = 3, probability= True)
k = 0.5
f = []
r = 0.000001
while(r<0.6):
    
    clf = SVC(kernel = 'rbf', degree = 3, probability= True, nu= r)
    x_train, x_test, y_train, y_test = get_data()
    #print ('------------- I am learning, yay! -------------')
    clf.fit(x_train, y_train)
    p = display_metrics(y_pred, y_test)
    f.append(p)
    r = r + 0.025

#y_pred = clf.predict(x_test)
#f = display_metrics(y_pred, y_test)
print(f)

E:\anaconda\lib\site-packages\scipy\io\wavfile.py:273: WavFileWarning: Chunk (non-data) not understood, skipping it.
  WavFileWarning)


the confusion matrix is  [[13  0  1  4]
 [ 0 22  2  1]
 [ 1  3  3  0]
 [ 1  1  0 16]]


KeyboardInterrupt: 

In [77]:
import sys
from utilities import get_data,display_metrics
from sklearn.svm import NuSVC as SVC

def get_model():
    return SVC(kernel = 'rbf', degree = 2, probability= True, nu = 0.7)

clf = SVC(kernel = 'rbf', degree = 2, probability= True, nu= 0.35)
x_train, x_test, y_train, y_test = get_data()
#print ('------------- I am learning, yay! -------------')
clf.fit(x_train, y_train)
display_metrics(y_pred, y_test)


E:\anaconda\lib\site-packages\scipy\io\wavfile.py:273: WavFileWarning: Chunk (non-data) not understood, skipping it.
  WavFileWarning)


the confusion matrix is  [[13  0  1  4]
 [ 0 22  2  1]
 [ 1  3  3  0]
 [ 1  1  0 16]]


(0.7941176470588235,)

In [58]:
o = []
o.append

In [33]:
i=0
k=0
m=0
l=0

for j in y_pred:
    if(j==3):
        i = i+1
    if(j==2):
        k=k+1
    if(j==1):
        l = l+1
    if(j==0):
        m = m+1
print(i,k,m,l)


21 11 13 23


In [26]:
import sys
from utilities import get_data,display_metrics
from sklearn.svm import LinearSVC as SVC
import numpy as np
import matplotlib.pyplot as plt
from itertools import cycle

from sklearn import svm, datasets
from sklearn.metrics import roc_curve, auc
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import label_binarize
from sklearn.multiclass import OneVsRestClassifier
from scipy import interp

def get_model():
    return SVC(multi_class = 'crammer_singer')

#clf = SVC(multi_class= 'crammer_singer')
x_train, x_test, y_train, y_test = get_data()
print ('------------- I am learning, yay! -------------')
#clf.fit(x_train, y_train)
print ('------------- I finished learning :) -------------')
classifier = OneVsRestClassifier(svm.SVC(kernel='linear', probability=True,
                                 random_state=random_state))
y_score = classifier.fit(x_train, y_train).decision_function(x_test)
#y_pred = clf.predict(x_test)
#display_metrics(y_pred, y_test)
fpr = dict()
tpr = dict()
roc_auc = dict()
for i in range(1):
    fpr[i], tpr[i], _ = roc_curve(y_test[:, i], y_score[:, i])
    roc_auc[i] = auc(fpr[i], tpr[i])

# Compute micro-average ROC curve and ROC area
fpr["micro"], tpr["micro"], _ = roc_curve(y_test.ravel(), y_score.ravel())
roc_auc["micro"] = auc(fpr["micro"], tpr["micro"])


E:\anaconda\lib\site-packages\scipy\io\wavfile.py:273: WavFileWarning: Chunk (non-data) not understood, skipping it.
  WavFileWarning)


------------- I am learning, yay! -------------
------------- I finished learning :) -------------


IndexError: too many indices for array

In [35]:
import sklearn.svm as svm

svm.NuSVC(probability=)

In [96]:
import sys
from utilities import get_data,display_metrics
from sklearn.svm import LinearSVC as SVC
from sklearn.metrics import accuracy_score
a= []
for i in range (1,3):
    clf = SVC(multi_class= 'ovr', max_iter=i)
    x_train, x_test, y_train, y_test = get_data()
    #print ('------------- I am learning, yay! -------------')
    clf.fit(x_train, y_train)
    #print ('------------- I finished learning :) -------------')
    y_pred = clf.predict(x_test)
    b = float(accuracy_score(y_pred=y_pred, y_true=y_test))
    a.append(b)
print(a)    
    




started reading folder Neutral


E:\anaconda\lib\site-packages\scipy\io\wavfile.py:273: WavFileWarning: Chunk (non-data) not understood, skipping it.
  WavFileWarning)


ended reading folder Neutral
started reading folder Angry
ended reading folder Angry
started reading folder Happy
ended reading folder Happy
started reading folder Sad
ended reading folder Sad
started reading folder Neutral
ended reading folder Neutral
started reading folder Angry
ended reading folder Angry
started reading folder Happy
ended reading folder Happy
started reading folder Sad
ended reading folder Sad
[0.6617647058823529, 0.5294117647058824]


In [98]:
!python utilities.py

python: can't open file 'utilities.py': [Errno 2] No such file or directory
